export const GET_QUESTS = 'GET_QUESTS'
export const GET_QUEST = 'GET_QUEST'
export const ADD_QUEST = 'ADD_QUEST'
export const DELETE_QUEST = 'DELETE_QUEST'

export const ADD_RESULT = 'ADD_RESULT'
export const GET_RESULTS ='GET_RESULTS'

export const GET_VISITORS = 'GET_VISITORS'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'